### ISSUE TITLE
Hi everyone. Got the traceback problem again.

### ISSUE THREAD

**Issue by johnpiers** [codeezer/livescore-cli#16] opened 2022-10-12 11:27 UTC
Hi everyone. Got the traceback problem again. 
```
Traceback (most recent call last):
  File "/usr/local/bin/livescore", line 60, in <module>
    main()
  File "/usr/local/bin/livescore", line 33, in main
    lsprint.table(lsweb.get_table(URL[k][1]), k)
  File "/opt/livescore-cli/lib/lsprint.py", line 129, in table
    team_name = each_row[1]
IndexError: string index out of range
```

_Originally posted by @johnpiers in https://github.com/codeezer/livescore-cli/issues/14#issuecomment-1115013774_
      
Just wondering if this project is dead in the water or if it's going to be continued. I posted about this issue 5 months ago and no one seems to be responding. Anyway thanks all the same.

**Comment by codeezer** [comment] 2023-01-29 23:19
Hey, we have worked on it and the issue is fixed now.

**Closed** 2023-01-29 23:20 UTC
